IF EXISTS ( SELECT  1 FROM  sys.objects WHERE   object_id = OBJECT_ID(N'dbo.vwProduct') AND type IN ( N'V' ) ) 
	DROP VIEW [dbo].[vwProduct]
GO


CREATE VIEW [dbo].[vwProduct]
AS


SELECT 
	p.Id,
	p.Name,
	p.ShortDescription,
	p.ERPDescription,
	p.ProductCode,
	p.PriceCode,
	p.UnitOfMeasure,
	p.Sku,
	p.Drawing,
	convert(nvarchar(10), p.ActivateOn, 101) ActivateOn,
	convert(nvarchar(10), p.DeactivateOn, 101) DeactivateOn,
	p.SortOrder,
	p.TaxCode1,
	p.TaxCode2,
	p.ShippingWeight,
	p.ShippingLength,
	p.ShippingWidth,
	p.ShippingHeight,
	p.ShippingAmountOverride,
	p.QtyPerShippingPackage,
	p.MetaKeywords,
	p.MetaDescription,
	p.PageTitle,
	p.ShippingClassification,
	p.PackDescription,
	p.DisplayPricePerPiece,
	p.UnitCost,
	p.UrlSegment,
	p.ContentManagerId,
	p.IsGiftCard,
	p.AllowAnyGiftCardAmount,
	p.ERPNumber,
	p.UPCCode,
	p.ERPManaged,
	p.ModelNumber,
	p.HandlingAmountOverride,
	p.IsSubscription,
	p.SubscriptionCyclePeriod,
	p.SubscriptionPeriodsPerCycle,
	p.SubscriptionTotalCycles,
	p.SubscriptionFixedPrice,
	p.SubscriptionAddToInitialOrder,
	p.SubscriptionShipViaId,
	p.SubscriptionAllMonths,
	p.SubscriptionJanuary,
	p.SubscriptionFebruary,
	p.SubscriptionMarch,
	p.SubscriptionApril,
	p.SubscriptionMay,
	p.SubscriptionJune,
	p.SubscriptionJuly,
	p.SubscriptionAugust,
	p.SubscriptionSeptember,
	p.SubscriptionOctober,
	p.SubscriptionNovember,
	p.SubscriptionDecember,
	p.VendorId,
	p.PriceBasis,
	p.UseVendorMarkup,
	p.TrackInventory,
	p.IsConfigured,
	p.TaxCategory,
	p.BasicListPrice,
	p.BasicSalePrice,
	convert(nvarchar(10), p.BasicSaleStartDate, 101) BasicSaleStartDate,
	convert(nvarchar(10), p.BasicSaleEndDate, 101) BasicSaleEndDate,
	p.StyleClassId,
	p.StyleParentId,
	p.SearchLookup,
	p.ReplacementProductId,
	p.HasMsds,
	p.IsHazardousGood,
	p.IsDiscontinued,
	p.ManufacturerItem,
	p.RoundingRule,
	p.MultipleSaleQty,
	p.Unspsc,
	p.IsSpecialOrder,
	p.IsFixedConfiguration,
	p.ConfigurationObjectId,
	p.IndexStatus,
	p.LowStockLevel,
	p.CreatedOn,
	p.CreatedBy,
	p.ModifiedOn,
	p.ModifiedBy,
	p.SearchBoost,
	p.IsSponsored,
	p.IsQuoteRequired,
	p.SalePriceLabel,
	p.UnitOfMeasureDescription,
	p.CustomAvailabilityMessage,
	p.ShipSeparately,
	p.DefaultVisibility,
	p.MinimumOrderQty,
	sc.Name StyleClassName,
	c.Html ProductDescription,
	v.VendorNumber VendorNumber,
	parentStyle.ERPNumber ParentStyleERPNumber
FROM
	dbo.Product p
	left join StyleClass sc on sc.Id = p.StyleClassId
	left join Content c on c.ContentManagerId = p.ContentManagerId
	left join Vendor v on v.Id = p.VendorId
	left join Product parentStyle on parentStyle.Id = p.StyleParentId
--where p.id = '62DE46BA-87FD-E711-A98C-A3E0F1200094'
/*
select * from vwProduct
*/
GO